# dashboard/utils/model_loader.py
"""Model loading with caching for PyMC InferenceData."""
import streamlit as st
import json
from pathlib import Path


@st.cache_resource
def load_trained_model():
    """Load trained PyMC model (InferenceData with posterior samples).

    Returns:
        InferenceData if model file exists, None otherwise

    Note:
        Cached with @st.cache_resource to load once per session.
        Model file should be generated by training script (Phase 4 final task).
    """
    model_path = Path(__file__).parent.parent.parent / "outputs" / "model_trace.nc"

    if not model_path.exists():
        return None

    import arviz as az  # lazy — only needed when model file actually exists

    try:
        return az.from_netcdf(model_path)
    except Exception as e:
        st.error(f"Failed to load model: {e}")
        return None


def load_scaler_params() -> dict:
    """Load feature scaler parameters from training data.

    Returns:
        Dict with mean/std for each feature used in standardization

    Note:
        These come from the training dataset, NOT from user uploads.
        Used to standardize prediction inputs to match training scale.
    """
    params_path = Path(__file__).parent.parent.parent / "models" / "scaler_params.json"

    if not params_path.exists():
        # Fallback to placeholder values
        return {"accommodates_mean": 3.2, "accommodates_std": 2.1}

    with open(params_path) as f:
        return json.load(f)
